version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ph_job_market_db
    restart: always
    environment:
      POSTGRES_DB: ph_job_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
